apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  restartPolicy: Always
  containers:
  - name: test
    image: busybox:latest
    ports:
    - containerPort: 80
      name: http
    - containerPort: 443
      name: https
    commands: ["/bin/sh", "-c"] ##this is entrypoint in docker image, this can be overridden by command in kubernetes
    args: ["echo Hello, World!"] ##this is CMD in docker image, this can be overridden by args in kubernetes